development:
  low:
    model: gpt-4.1-nano
    provider: openai
  medium:
    model: gpt-5.4-mini
    provider: openai
  high:
    model: gpt-5.4-mini
    provider: openai
  embedding:
    model: nomic-embed-text
    provider: openai
test:
  low:
    model: qwen2.5:3b
    provider: openai
  medium:
    model: qwen2.5:3b
    provider: openai
  high:
    model: qwen2.5:3b
    provider: openai
  embedding:
    model: nomic-embed-text
    provider: openai
production:
  low:
    model: claude-haiku-4-5
    provider: anthropic
  medium:
    model: claude-sonnet-4-6
    provider: anthropic
  high:
    model: claude-opus-4-6
    provider: anthropic
  embedding:
    model: nomic-embed-text
    provider: openai
