source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "propshaft"
gem "pg", "~> 1.5"
gem "neighbor"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rspec-rails"
  gem "capybara"
  gem "turnip"
  gem "capybara-playwright-driver"
  gem "rspec-openapi"
  gem "puma" # for javascript capybara tests
end

group :development do
  gem "standard", require: false
  gem "yaml-sort", require: false
end

gem "omniauth"
gem "doorkeeper"
gem "omniauth-rails_csrf_protection"
gem "async-job-adapter-active_job"
gem "falcon"
gem "phlex-rails"
gem "literal"
gem "noticed"
gem "rails_pulse"
gem "ruby_llm"
gem "kaminari"
