source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.2"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
# gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rspec-rails"
  gem "capybara"
  gem "turnip"
  gem "playwright-ruby-client"
  gem "rspec-openapi"
  gem "puma" # for javascript capybara tests
end

group :development do
  gem "standard", require: false
  gem "yaml-sort", require: false
end

gem "omniauth"
gem "omniauth-rails_csrf_protection"
gem "async-cable"
gem "async-job-adapter-active_job"
gem "async-websocket"
gem "falcon"
gem "falcon-limiter"
gem "live"
gem "phlex-rails"
gem "literal"
gem "noticed"
gem "rails_pulse"
gem "jsbundling-rails"
gem "cssbundling-rails"
